controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (runner.y > 70) {
        runner.vy = -140
        runner.startEffect(effects.halo, 500)
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    game.over(false, effects.slash)
})
let projectile: Sprite = null
let runner: Sprite = null
tiles.setCurrentTilemap(tilemap`level1`)
runner = sprites.create(img`
    .....6eeeeeeeeeece6.....
    ....6776eeeeeeeee676....
    ...6776666eeee6766776...
    ..6776ee77777777667776..
    ...668ce7768867788666...
    ......ce77eeee67ee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......eeeeeeeeeeee......
    ......beeeeeeeeeeb......
    .......beeeeeeeeb.......
    ........beeeeeeb........
    `, SpriteKind.Player)
runner.ay = 330
scene.setBackgroundColor(9)
runner.setPosition(20, 0)
let speed = -100
game.onUpdate(function () {
    info.changeScoreBy(1)
})
game.onUpdateInterval(1000, function () {
    speed += randint(-1, -5)
    if (Math.percentChance(40)) {
        projectile = sprites.createProjectileFromSide(img`
            ...............ff.......
            .............ff2ffff....
            ............ff2feeeeff..
            ...........ff22feeeeeff.
            ...........feeeeffeeeef.
            ..........fe2222eefffff.
            ..........f2effff222efff
            ..........fffeeeffffffff
            ..........fee44fbe44efef
            ...........feddfb4d4eef.
            ..........c.eeddd4eeef..
            ....ccccccceddee2222f...
            .....dddddcedd44e444f...
            ......ccccc.eeeefffff...
            ..........c...ffffffff..
            ...............ff..fff..
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `, speed, 0)
        projectile.ax = -5
        projectile.y = 76
    }
})
